// sveltelexi/src/lib/morestuff/Search.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { usewsstore } from './websocketsearch';
  import '../../routes/Layout.css';

  let { classNameform = '', classNameinput = '', classnamebutton = '' } = $props();

  const { connect, disconnect, sendsearch } = usewsstore.getState();

  let isFocused = $state(false);
  let matches = $state(usewsstore.getState().matches);
  let inputRef: HTMLInputElement;

  $effect(() => usewsstore.subscribe((s) => (matches = s.matches)));

  async function onSubmit(e: SubmitEvent) {
    e.preventDefault();
    inputRef?.blur();
    disconnect();
    const username = new FormData(e.currentTarget as HTMLFormElement).get('user') as string;
    const match = matches.length && matches[0].n[0].toLocaleLowerCase().includes(username.toLocaleLowerCase());
    const id = match ? matches[0].id : username;
    await goto(`/${encodeURIComponent(id)}`);
  }

  async function onsuggest(id: string) {
    disconnect();
    await goto(`/${encodeURIComponent(id)}`);
  }

  function focused() {
    connect();
    isFocused = true;
  }

  function blurred() {
    setTimeout(() => (isFocused = false), 200);
  }
</script>
<div class = "flexstuff" style = "width:100%">
<div class="flexstuff" onfocusout={blurred}>
  <form class={classNameform} onsubmit={onSubmit}>
    <input
      bind:this={inputRef}
      autocorrect="off"
      spellcheck="false"
      autocomplete="off"
      name="user"
      class={classNameinput}
      placeholder="Enter somones profile link, Steamid or Name"
      onfocus={(e) => { focused(); e.currentTarget.select(); sendsearch(e.currentTarget.value); }}
      oninput={(e) => { focused(); sendsearch(e.currentTarget.value); }}
    />
    <button type="submit" class={classnamebutton}>Search</button>
  </form>
  <div style="position: relative; width: 100%" >
    {#if isFocused && matches.length}
      <div class="searchsuggestionholder">
        {#each matches as { n, id, a, g }, index (index)}
          <button type="button" class="suggestion{!index ? ' importantsuggestion' : ''}" onclick={() => onsuggest(id)}>
            <img
              style="height: 100%"
              src={`https://avatars.fastly.steamstatic.com/${a ? a : 'fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb'}.jpg`}
              alt=""
            />
            <div class="suggestionname">
              {n[0]} {#each n.slice(1) as name, i}<span class="subsuggestionname{i}">{name}</span>{/each}
            </div>
            {#if g != 0}<span class="logcounter">{g == 1 ? '1 Log' : `${g} Logs`}</span>{/if}
          </button>
        {/each}
        <div class="notice">Log counts are only for usernames that match the search</div>
      </div>
    {/if}
  </div>
</div>
</div>

// lexifront/components/Search.tsx
import { navigate } from "vike/client/router";
import React from "react";
import { usewsstore } from "./websocketsearch";
interface testProps {
  classNameform?: string;
  classNameinput?: string;
  classnamebutton?: string;
}

// export const Test: React.FC<testProps> = ({ className }) => {
//   return <div className={className}>Test</div>;
// };

export default function Prettysearch({
  classNameform,
  classNameinput,
  classnamebutton,
}: testProps) {
  const [isFocused, setIsFocused] = React.useState(false);
  const inputRef = React.useRef<HTMLInputElement>(null);

  async function onSubmit(formData: FormData) {
    // console.log("pants")
    inputRef.current?.blur();
    disconnect();
    const username = formData.get("user") as string;
    const match = matches.length && matches[0].n.includes(username)
    // console.log("match",match)
    const id = match ? matches[0].id : username;
    // console.log("id",id)
    const navigationPromise = navigate(
      `/${encodeURIComponent(id)}`,
    );
    console.log("The URL changed but the new page hasn't rendered yet.");
    await navigationPromise;
    console.log("The new page has finished rendering.");
  }
  async function onsuggest(formData: string) {
    // console.log("HERE")
    disconnect();
    const navigationPromise = navigate(`/${encodeURIComponent(formData)}`);
    console.log("The URL changed but the new page hasn't rendered yet.");
    await navigationPromise;
    console.log("The new page has finished rendering.");
  }
  const { connect, disconnect, matches, sendsearch , count} =
    usewsstore();


  function focused() {
    connect();
    setIsFocused(true);
  }

  function blurred() {
    setTimeout(() => setIsFocused(false), 200);
  }
  return (
    <div className="flexstuff" onBlur={blurred}>
      <form action={onSubmit} className={classNameform}>
        <input
          ref={inputRef}
          autoCorrect="off"
          spellCheck="false"
          autoComplete="off"
          name="user"
          onFocus={(e) => {
            focused();
            sendsearch(e.target.value);
          }}
          onChange={(e) => {
            focused();
            sendsearch(e.target.value);
          }}
          className={classNameinput}
          placeholder="Enter somones profile link, or a steamid"
        />
        <button type="submit" className={classnamebutton}>
          Search
        </button>
      </form>
      <div style={{ position: "relative", width: "100%" }}>
        {isFocused  && matches.length ?  (
          <div className="searchsuggestionholder">
            {" "}
          
            {matches.map(({ n, id, a, g }, index) => {
              return (
                <a
                  className={`suggestion${!index ? " importantsuggestion" : ""}`}
                  onClick={() => {
                    onsuggest(id);
                  }}
                  key={index}
                >
                  <img style={{ "height": "100%" }}
                    src={`https://avatars.fastly.steamstatic.com/${a ? a : "fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb"}.jpg`}
                  ></img>
                  <div className="suggestionname"
                    
                  
                  >
                    {n[0]} {n.slice(1).map((name, index) => (<span className={`subsuggestionname${index}`} key={index}>{name}</span>))}
                  </div>
                  <span className="logcounter">{g == 1 ? "1 Log" : `${g} Logs`}</span>
                  {/* {" "} <span className="">{id}</span> */}
                  {" "}
                </a>
              );
            })}{" "}  <div className="notice">Log counts are only for usernames that match the search</div>
          </div>
) : (
          ""
        )}
      </div>
    </div>
  );
}
